---
title: "K Nearest Neighbors (KNN)"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<center>

# Jesse A. Flowers

Adkerson School of Accountancy

Mississippi State University

Jesseflow99@gmail.com

</center>

------------------------------------------------------------------------
# (KNN) Using Iris Data Set

## Split The Data 60/40 
```{r,echo=TRUE}
library(caret)
trainIndexKNN <- createDataPartition(iris$Species, p = .6, list = FALSE, times = 1)
 
```

## Grab The Data
```{r,echo=TRUE}
#grab the data
irisTrainKNN <- iris[ trainIndex,]
irisTestKNN  <- iris[-trainIndex,]
```


## Perform PreProcessing on Data
```{r,echo=TRUE}
preProcValuesKNN <- preProcess(irisTrain, method = c("center", "scale"))

trainTransformedKNN <- predict(preProcValuesKNN, irisTrain)

preProcValuesKNN <- preProcess(irisTest, method = c("center", "scale"))

testTransformedKNN <- predict(preProcValuesKNN, irisTest)
psych::describe(testTransformed)
```

## Fit KNN 
```{r,echo=TRUE}
knn_fit<-train(Species~.,
               data=trainTransformedKNN,
               method="knn",
               tuneGrid=data.frame(k=5))

knn_fit


```


## Use the test set to make a prediction
```{r,echo=TRUE}

knn_pred<-predict(knn_fit,testTransformedKNN)
head(knn_pred)

```

## Run ConfusionMatrix 

```{r,echo=TRUE}
confusionMatrix(knn_pred,testTransformedKNN$Species)

```



