---
title: "Resume"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<center>

# Jesse A. Flowers

Adkerson School of Accountancy

Mississippi State University

Jesseflow99@gmail.com

</center>

------------------------------------------------------------------------

## EMPLOYMENT

### *Miles Tax Service*,  
Starkville, MS — Accountant 
February 2020- May 2021
 
### *Walmart*, 
 Starkville, MS — Automotive Associate 
May 2018- March 2020 
 
### *Car Wash USA*,  
Olive Branch, MS — Supervisor/Key Holder 
April 2015 -August 2018 
 
 
## EDUCATION

### *Mississippi State University, Starkville, MS*,
Master of Taxation (Minor in Data Analytics)  
Graduation Date July 2022

### *Mississippi State University, Starkville, MS*, 
Bachelors of Accountancy  
Graduation Date April 2021

## Skills and Abilities 
 
•	Advised clients on business and personal tax decisions. 

•	Resolved tax issues for corporate and personal tax clients. 

•	Obtained extensive experience in multiple computer programs such as QuickBooks,        Proseries, and Excel. 

•	Executed large collaborative projects.

•	Written and oral communication skills. 

•	Excellent collaborative skills. 
 
 
## Honors and Organizations 
 
•	Accounting and Finance Student Society of Mississippi State University 

•	President’s list at Mississippi State 
